apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: loggers.example.com
spec:
  group: example.com
  versions:
  - name: v1
    served: true
    storage: true
  names:
    kind: Logger
    plural: loggers
  scope: Namespaced
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["name", "timeInterval"]
          properties:
            name:
              type: "string"
              minimum: 1
            timeInterval:
              type: "integer"
              minimum: 1